version: '3'
services:
  minio1:
    container_name: minio1
    image: 'bitnamilegacy/minio:2025.4.22'
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - /minio1_data1:/bitnami/minio/data-1
      - /minio1_data2:/bitnami/minio/data-2
      - /minio1_data3:/bitnami/minio/data-3
      - /minio1_data4:/bitnami/minio/data-4
      - certs1:/certs
    environment:
      - MINIO_ROOT_USER=default
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=172.101.0.{11...14}/bitnami/minio/data-{1...4}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:4
      - MINIO_STORAGE_CLASS_RRS=EC:2
    networks:
      network:
        ipv4_address: 172.101.0.11

  minio2:
    container_name: minio2
    image: 'bitnamilegacy/minio:2025.4.22'
    volumes:
      - /minio2_data1:/bitnami/minio/data-1
      - /minio2_data2:/bitnami/minio/data-2
      - /minio2_data3:/bitnami/minio/data-3
      - /minio2_data4:/bitnami/minio/data-4
      - certs2:/certs
    environment:
      - MINIO_ROOT_USER=default
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=172.101.0.{11...14}/bitnami/minio/data-{1...4}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:4
      - MINIO_STORAGE_CLASS_RRS=EC:2
    networks:
      network:
        ipv4_address: 172.101.0.12

  minio3:
    container_name: minio3
    image: 'bitnamilegacy/minio:2025.4.22'
    volumes:
      - /minio3_data1:/bitnami/minio/data-1
      - /minio3_data2:/bitnami/minio/data-2
      - /minio3_data3:/bitnami/minio/data-3
      - /minio3_data4:/bitnami/minio/data-4
      - certs3:/certs
    environment:
      - MINIO_ROOT_USER=default
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=172.101.0.{11...14}/bitnami/minio/data-{1...4}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:4
      - MINIO_STORAGE_CLASS_RRS=EC:2
    networks:
      network:
        ipv4_address: 172.101.0.13

  minio4:
    container_name: minio4
    image: 'bitnamilegacy/minio:2025.4.22'
    volumes:
      - /minio4_data1:/bitnami/minio/data-1
      - /minio4_data2:/bitnami/minio/data-2
      - /minio4_data3:/bitnami/minio/data-3
      - /minio4_data4:/bitnami/minio/data-4
      - certs4:/certs
    environment:
      - MINIO_ROOT_USER=default
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=172.101.0.{11...14}/bitnami/minio/data-{1...4}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:4
      - MINIO_STORAGE_CLASS_RRS=EC:2
    networks:
      network:
        ipv4_address: 172.101.0.14

networks:
  network:
    name: minio-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.101.0.0/24
          gateway: 172.101.0.1

volumes:
  certs1:
    driver: local
  certs2:
    driver: local
  certs3:
    driver: local
  certs4:
    driver: local